name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production --base-href /portfolio/

      - name: Create 404.html fallback
        run: |
          cp dist/portfolio-app/index.html dist/portfolio-app/404.html
          sed -i 's/<base href="\/portfolio\/">/<base href="\/">/g' dist/portfolio-app/404.html

      - name: Disable Jekyll processing
        run: touch dist/portfolio-app/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio-app
          enable_jekyll: false
